name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.adminCommand({ ping: 1 })'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install server dependencies
        working-directory: ./server
        run: npm ci

      - name: Run server unit tests
        working-directory: ./server
        run: npm test

      - name: Start server
        working-directory: ./server
        env:
          MONGODB_URI: mongodb://127.0.0.1:27017/ci_test_db
          PORT: 5000
          JWT_SECRET: testsecret
        run: |
          npm run dev &
          # wait for port 5000
          for i in {1..30}; do
            if nc -z localhost 5000; then
              echo "server up"; break
            fi
            echo "waiting..."; sleep 1
          done

      - name: Run server smoke test
        working-directory: ./server
        env:
          API_URL: http://localhost:5000/api
        run: npm run smoke

      - name: Install client and build
        working-directory: ./client
        run: |
          npm ci
          npm run build
